spring:
  cloud:
    stream:
      bindings:
        bento4_hls:
          destination: bento4.hls
          group: s1
          contentType: application/json
        tube_hls:
          destination: tube.hls
          group: s1
          contentType: application/json