spring:
  cloud:
    stream:
      bindings:
        ffmpeg_queue:
          destination: ffmpeg.queue
          group: s1
          contentType: application/json
        ffmpeg_converter_pop:
          destination: ffmpeg.converter
          group: s1
          contentType: application/json
        ffmpeg_converter_push:
          destination: ffmpeg.converter
          group: s1
          contentType: application/json
        bento4_hls:
          destination: bento4.hls
          group: s1
          contentType: application/json
        tube_info:
          destination: tube.info
          group: s1
          contentType: application/json
      rabbit:
        bindings:
          ffmpeg_converter_pop:
            consumer:
              max-priority: 20