spring:
  cloud:
    stream:
      bindings:
        tube_store:
          destination: tube.store
          group: s1
          contentType: application/json
        file_queue:
          destination: file.queue
          group: s1
          contentType: application/json
  servlet:
    multipart:
      max-file-size: 200MB