spring:
  cloud:
    stream:
      bindings:
        tube_hls:
          destination: tube.hls
          group: s1
          contentType: application/json
        tube_info:
          destination: tube.info
          group: s1
          contentType: application/json
        tube_store:
          destination: tube.store
          group: s1
          contentType: application/json
        ffmpeg_queue:
          destination: ffmpeg.queue
          group: s1
          contentType: application/json
        indexing_queue:
          destination: indexing.queue
          group: s1
          contentType: application/json
        file_queue:
          destination: file.queue
          group: s1
          contentType: application/json
        torrent_queue:
          destination: torrent.queue
          group: s1
          contentType: application/json
  servlet:
    multipart:
      max-file-size: 200MB
---

spring:
  profiles: prod
  data:
    mongodb:
      database: ${vcap.services.TUBE_MONGODB.credentials.path}
      port: ${vcap.services.TUBE_MONGODB.credentials.port}
      password: ${vcap.services.TUBE_MONGODB.credentials.password}
      username: ${vcap.services.TUBE_MONGODB.credentials.username}
      host: ${vcap.services.TUBE_MONGODB.credentials.hostname}

---

spring:
  profiles: dev
  data:
    mongodb:
      database: tube